---
- name: Secure Data Deployment
  hosts: local
  vars_files:
    - secrets.yml # Ansible will automatically try to decrypt this

  tasks:
    - name: Show that we can read the secret
      debug:
        msg: "The database password is {{ db_password }}"
